CREATE TABLE IF NOT EXISTS tt_saves (player TEXT PRIMARY KEY, rev INTEGER NOT NULL, state TEXT NOT NULL, updated INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS tt_history (id INTEGER PRIMARY KEY AUTOINCREMENT, player TEXT NOT NULL, rev INTEGER NOT NULL, state TEXT NOT NULL, at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS tt_history_player ON tt_history (player, id);
